feat: APM 预计算关联指标导出分钟汇总 & 新指标接入 --story=118081305
TencentBlueKing/bkmonitor-datalink pull request #397
Opened 2024-06-26 06:57 UTC by rxwycdh

2024-06-26 07:10 UTC, rxwycdh commented on pkg/bk-monitor-worker/config/apm_config.go
> +	MetricsInMemDuration = GetValue("taskConfig.apmPreCalculate.metricsReport.memoryDuration", 10*time.Minute, viper.GetDuration)
MetricsInMemDuration：配置去重后指标最长在内存中保留多久时间，再统一上报（上报间隔）

2024-06-26 07:10 UTC, rxwycdh commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/builder.go
> +			isUpdated := core.GetMetadataCenter().CheckUpdate(p.startInfo.DataId)
监听 consul 更变然后重启任务

2024-06-26 07:10 UTC, rxwycdh commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/window/metrics_processor.go
> +) {
findSpanMetric发现的是 xxx_relation 指标（直接通过 span 来发现）

2024-06-26 07:10 UTC, rxwycdh commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/window/metrics_processor.go
> +			name := "apm_service_to_apm_service_flow"
findParentChildMetric发现的是 xxx_flow 指标（通过 父子关系 来发现）

2024-08-28 13:39 UTC, rxwycdh commented on pkg/bk-monitor-worker/cmd/apm/start_from_file.go
> +func listenFile(cmd *cobra.Command, args []string) {
单机模式启动，不依赖 web，scheduler 进程，用来测试预计算的

2024-08-28 13:39 UTC, rxwycdh commented on pkg/bk-monitor-worker/config/apm_config.go
> +	DurationBuckets = []float64{0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2, 2.5, 5}
flow 指标的耗时 bucket

2024-08-28 13:39 UTC, rxwycdh commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/builder.go
> +			isUpdated, diff := core.GetMetadataCenter().CheckUpdate(p.startInfo.DataId)
增加监听 apm 应用的 consul 配置更新，如果有更新，则重启任务

2024-08-28 13:39 UTC, rxwycdh commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/core/types.go
> +	}
增加预计算四个标准字段，都是写在 resource 的，关联指标上报时会取出来

2024-08-28 13:39 UTC, rxwycdh commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/models/custom_service_config.go
> +package models
这两个文件都是从 bk-collector 自定义服务复制过来的，因为flow指标需要对自定义服务也计算指标，所以需要知道应用的自定义服务配置是什么，支持直接取“peer.service” 字段 和 从数据库获取（默认是从peer_service 字段获取），这里是从数据库获取自定义服务进行匹配并获取匹配后的名称

2024-08-28 13:39 UTC, rxwycdh commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/storage/metrics_collector.go
> +)
这个文件是将计算好的指标转换为 prom remotewrite 格式的逻辑，这里是转换的逻辑，计算指标的逻辑在 metrics_processor 文件里面

2024-08-28 13:39 UTC, rxwycdh commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/storage/metrics_handler.go
> +) *MetricDimensionsHandler {
这里是控制指标定时上报的逻辑，分为 flow 指标的定时上报，relation 指标的定时上报，分为两个 goroutine 来实现，各自有各自的定时器。

2024-08-28 13:39 UTC, rxwycdh commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/window/metrics_processor.go
> +
此文件是指标的计算逻辑，所有指标都在这里计算，relation 指标还有 system -> system 的关系，属于 4 层关联，默认不开启

2024-08-28 13:39 UTC, rxwycdh commented on pkg/bk-monitor-worker/utils/remote/prometheus.go
> +	if !p.isValid || len(writeReq.Timeseries) == 0 {
@shamcleren prometheus 这里改动了，参数为 prompb.WriteRequest，之前是 timeseries，这两个结构可以直接转换出来，其他逻辑没变。

2024-08-28 13:39 UTC, rxwycdh commented on pkg/bk-monitor-worker/utils/remote/prometheus.go
> +	maps.Copy(h, headers)
@shamcleren 这里newPrometheusCLient改动了一下，如果调用时，传递了 token，那么 token 就会固定下来， WriteBatch 的 token 参数为空时就用这个默认的。

2024-08-28 13:39 UTC, rxwycdh commented on pkg/bk-monitor-worker/utils/remote/space_reporter.go
> +	writer := NewPrometheusWriterClient("", writerUrl, map[string]string{})
这里改动了一下，去除了 enabled 配置，prometheus 的 Client 默认开启，然后改为了直接传递 url 和 header

2024-08-28 13:39 UTC, rxwycdh commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/window/metrics_processor.go
> +		// 在这个 trace 里面它是孤独节点 此次调用就需要记录而不需要理会这个节点是否发生了调用关系
孤独节点是什么？
在 trace 里面只有主调没有被调，或者只有被调没有主调的节点，需要将这些 span 也进行计算，这些 span 缺失的一方，可能是在另外的平台，这里也需要纳入进去，计算出此服务 “调用其他服务的主调耗时”、此服务“被其他服务调用的耗时”

2024-09-04 08:48 UTC, liuwenping requested changes

2024-09-04 08:48 UTC, liuwenping commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/builder.go
> +			isUpdated := core.GetMetadataCenter().CheckUpdate(p.startInfo.DataId)
疑问：consul本身是不是有watch的能力，这里为什么是10分钟的周期去查询的？

2024-09-04 08:48 UTC, liuwenping commented on pkg/bk-monitor-worker/utils/remote/prometheus.go
> +		h[tokenKey] = h["x-bk-token"]
header的这个key是大写

2024-09-04 08:48 UTC, liuwenping commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/models/custom_service_config.go
> +package models
协议头需要保留，另外需要额外增加 copy 的github路径

2024-09-04 09:17 UTC, chenjiandongx commented on pkg/bk-monitor-worker/cmd/apm/start_from_file.go
> +		panic(err)
建议使用 logger.Fatal 保持与上面一致的行为。

2024-09-04 09:17 UTC, chenjiandongx commented on pkg/bk-monitor-worker/cmd/apm/start_from_file.go
> +package apm
请全区检查 license 头

2024-09-04 09:18 UTC, chenjiandongx commented on pkg/bk-monitor-worker/config/config.go
> +		panic(fmt.Sprintf("failed to get float slice of key: %s, error: %s", key, err))
这么严重吗，取不到就要 panic？

2024-09-04 10:47 UTC, rxwycdh commented on pkg/bk-monitor-worker/utils/remote/prometheus.go
> +		h[tokenKey] = h["x-bk-token"]
const (
	tokenKey = "X-BK-TOKEN"
)
这个是大写，这里小写是兼容配置文件里面填了小写时候的情况

2024-09-04 11:06 UTC, rxwycdh commented on pkg/bk-monitor-worker/config/config.go
> +		panic(fmt.Sprintf("failed to get float slice of key: %s, error: %s", key, err))
这个方法只有在启动的时候才执行的，说明配置有问题，得退出

2024-09-04 12:35 UTC, chenjiandongx commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/core/meta.go
> +	logger.Warnf("😱 Create fake consulClient, make sure you guys are not in production!!!")
💯

2024-09-04 12:40 UTC, chenjiandongx commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/storage/metrics_collector.go
> +		if len(composition) == 2 {
这个建议抽出来一个函数返回 labels，三层 if 看起来有点多。

2024-09-04 12:41 UTC, chenjiandongx commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/storage/metrics_collector.go
> +	ts := time.Now().UnixNano() / int64(time.Millisecond)
为什么不直接使用 `time.Now().UnixMilli()` ?

2024-09-04 12:41 UTC, chenjiandongx commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/storage/metrics_collector.go
> +	ts := time.Now().UnixNano() / int64(time.Millisecond)
同上

2024-09-04 12:46 UTC, chenjiandongx commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/window/metrics_processor.go
> +		serviceInstanceRelationLabelKey := fmt.Sprintf(
建议这里使用函数来处理，比如

```golang
func pair(k, v string) string { return k + "=" + v}

// 然后 append 成一个列表，最后再 strings.Join(pairs, ",")
```

2024-09-04 12:46 UTC, chenjiandongx commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/window/metrics_processor.go
> +				"%s=%s,%s=%s,%s=%s,%s=%s,%s=%s%s=%s,%s=%d,%s=%s,%s=%s,%s=%s,%s=%s,%s=%s,%s=%d,%s=%v,%s=%v",
同上，这代码看起来很可怕

2024-09-04 12:50 UTC, chenjiandongx commented on pkg/bk-monitor-worker/store/mock_store_.go
> +// Code generated by MockGen. DO NOT EDIT.
这个 mock_store_.go 的文件名是怎么回事？一般不是会以 _gen 结尾吗

2024-09-04 13:02 UTC, rxwycdh commented on pkg/bk-monitor-worker/cmd/apm/start_from_file.go
> +package apm
已处理

2024-09-04 13:03 UTC, rxwycdh commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/core/meta.go
> +	logger.Warnf("😱 Create fake consulClient, make sure you guys are not in production!!!")
已解决

2024-09-04 13:13 UTC, rxwycdh commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/storage/metrics_collector.go
> +		if len(composition) == 2 {
已优化

2024-09-05 02:00 UTC, liuwenping approved these changes

2024-09-05 02:00 UTC, rxwycdh commented on pkg/bk-monitor-worker/cmd/apm/start_from_file.go
> +		panic(err)
已解决

2024-09-05 02:01 UTC, rxwycdh commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/window/metrics_processor.go
> +		serviceInstanceRelationLabelKey := fmt.Sprintf(
已解决

2024-09-05 02:01 UTC, rxwycdh commented on pkg/bk-monitor-worker/store/mock_store_.go
> +// Code generated by MockGen. DO NOT EDIT.
已解决

2024-09-05 02:01 UTC, rxwycdh commented on pkg/bk-monitor-worker/internal/apm/pre_calculate/storage/metrics_collector.go
> +	ts := time.Now().UnixNano() / int64(time.Millisecond)
已解决

2024-09-05 02:43 UTC, merged