feat:[libgse] add output bkcollector
TencentBlueKing/bkmonitor-datalink pull request #9
Opened 2023-10-30 02:19 UTC by snhwade

2023-10-30 03:59 UTC, liuwenping requested changes

2023-10-30 03:59 UTC, liuwenping commented on pkg/libgse/output/bkcollector/bkcollector.go
> +	err = BkCollectorConnect(ip, port)
1. 这个的取名，要改一改。看了下逻辑是在做一个check的动作，建议使用类似checkXXX的方法。
2. 另外，这个check的逻辑建议滞后，不用在make的时候报错，而是后续通过不断check的方式来检测

2023-10-30 03:59 UTC, liuwenping commented on pkg/libgse/output/bkcollector/config.go
> +	MonitorID: 295,
bkcollector里为啥需要monitorid这个配置。 而且这里写了一个固定的数字

2023-10-30 03:59 UTC, liuwenping commented on pkg/libgse/output/bkcollector/bkcollector.go
> +		Items := mapItem["items"].([]interface{})
代码中很多类似的类型转换逻辑`val.(type)`，需要增加转换失败处理。 否则会panic

2023-10-30 03:59 UTC, liuwenping commented on pkg/libgse/output/bkcollector/client.go
> +		logp.Err("bkcollector 服务无法连接, %v", err)
建议：日志使用英文打印

2023-10-30 09:59 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/bkcollector.go
> +		return nil
这个错误建议打日志

2023-10-30 10:00 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/bkcollector.go
> +		Items := mapItem["items"].([]interface{})
另外，函数内的变量不建议用大写命名

2023-10-30 10:01 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/bkcollector.go
> +	if err != nil {
这里出错，不返回 nil 吗，这个 exp 看起来已经不可用了

2023-10-30 10:01 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/bkcollector_test.go
> +	"github.com/stretchr/testify/assert"
import 格式化

2023-10-30 10:02 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/bkcollector_test.go
> +
函数末尾不需要留空行

2023-10-30 10:02 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/bkcollector_test.go
> +func TestNewOutput(t *testing.T) {
函数之间请使用空行隔开

2023-10-30 10:03 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/client.go
> +		defer conn.Close()
在 err 的情况下，conn 应该是 nil，此时再调用 `conn.Close`，那就直接 panic 了

2023-10-30 10:04 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/data.go
> +func getSpanId(spanId string) [8]byte {
同理，建议做代码格式检查

2023-10-30 10:05 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/data.go
> +		v, _ := value.(string)
忽略断言失败的原因是什么？另外不建议使用下划线命名

2023-10-30 10:06 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/data.go
> +	var result = make([]attribute.KeyValue, 0, 0)
make 的时候，len 与 cap 一致的时候只写一个即可

2023-10-30 10:06 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/data.go
> +		logp.Err("traceState err! ")
请携带 err 具体内容

2023-10-30 10:07 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/data.go
> +func CreateSpanContext(spanId [8]byte, traceId [16]byte, traceState string) trace.SpanContext {
同上，函数内不建议用大写变量

2023-10-30 10:08 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/data.go
> +package bkcollector
pre-commit 应该会补上 header 头

2023-10-30 10:09 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/bkcollector.go
> +func (c *Output) Close() error {
为什么不考虑直接返回 `c.exporter.Shutdown(context.Background())`，这里需要对外隐藏 error 的原因是什么？

2023-10-30 10:10 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/bkcollector.go
> +		logp.Err("unpack config error, %v", err)
这里的 error 需要打印，下面的其他 error 不需要打印的原因是什么

2023-11-01 14:58 UTC, liuwenping requested changes

2023-11-01 14:58 UTC, liuwenping commented on pkg/libgse/output/bkcollector/bkcollector.go
> +package bkcollector
文件头需要补充一下
本地装一下pre-commit, 这些问题在提交时即可发现

2023-11-01 14:58 UTC, liuwenping commented on pkg/libgse/output/bkcollector/bkcollector.go
> +	//
这里是漏写注释了吗。看到有个注释，但是内容是空

2023-11-01 14:58 UTC, liuwenping commented on pkg/libgse/output/bkcollector/bkcollector.go
> +	output := NewOutput(c.GrpcHost, c.BkDataToken)
从NewOutput的实现来看，这里的返回值一定不会是nil，这里的if判断看上去多余了

2023-11-01 14:58 UTC, liuwenping commented on pkg/libgse/output/bkcollector/bkcollector.go
> +	return outputs.Success(int(c.EventBufferMax), 0, output)
看了下代码，`EventBufferMax`这个配置是批次大小，`defaultConfig`这里也未给出初始值，那么这里会是一个0。需要确认下这里的行为是否符合预期

2023-11-01 15:51 UTC, liuwenping requested changes

2023-11-01 15:51 UTC, liuwenping commented on pkg/libgse/output/bkcollector/bkcollector.go
> +		items := data.String()
这里的data本身就是一个map对象，没看懂为啥要调用一次data.String()，将data转成一个字符串，然后下面又使用ToMap(实现上是json.Unmarshal方法)转换为map

2023-11-01 15:51 UTC, liuwenping commented on pkg/libgse/output/bkcollector/bkcollector.go
> +func (c *Output) Publish(batch publisher.Batch) error {
输入的event数据格式和输出的格式，建议增加一个类型配置，需要由外层传递进来。这里不能直接假定一定是日志的格式，输出也不能假定直接是trace的格式

2023-11-01 15:51 UTC, liuwenping commented on pkg/libgse/output/bkcollector/bkcollector.go
> +			continue
这里地方如果转换失败，建议增加日志输出，可以是Debug级别的输出，需要告知哪里失败了。
底下的几个continue也是类似的，都需要增加日志

2023-11-01 15:51 UTC, liuwenping commented on pkg/libgse/output/bkcollector/bkcollector.go
> +		makeItems, toMakeItems := mapItem["items"].([]interface{})
golang一点的写法，第二个参数名，一般写成ok，类似 `aStr, ok := a.(string)`写法

2023-11-01 15:51 UTC, liuwenping commented on pkg/libgse/output/bkcollector/bkcollector.go
> +			mapLog := ToMap(log)
这里建议定义成一个结构体的形式，然后使用json.Unmarshal，直接转换成一个结构体，而不是统一都转成map的形式

2023-11-01 16:16 UTC, liuwenping requested changes

2023-11-01 16:16 UTC, liuwenping commented on pkg/libgse/output/bkcollector/bkcollector.go
> +	bkdatatoken string
这里的取名需要统一，一般是驼峰。如果要公开，那么首字母就大写

2023-11-01 16:16 UTC, liuwenping commented on pkg/libgse/output/bkcollector/bkcollector.go
> +			time.Sleep(time.Minute)
这个interval这么大的么，测试过了没有

2023-11-01 16:16 UTC, liuwenping commented on pkg/libgse/output/bkcollector/bkcollector.go
> +		if err != nil {
对这个err的判断为什么要整两个if，正常就是一个if else，不需要两次判断

2023-11-01 16:16 UTC, liuwenping commented on pkg/libgse/output/bkcollector/bkcollector.go
> +		logp.Err("failed to create a new collector exporter: %v", err)
这里报错之后只是打印了一行日志，那什么时候会再次new这个exporter呢。貌似后面的代码中都没有看到

2023-11-01 16:16 UTC, liuwenping commented on pkg/libgse/output/bkcollector/data.go
> +package bkcollector
同样的，需要补充头部信息

2023-11-01 16:16 UTC, liuwenping commented on pkg/libgse/output/bkcollector/data.go
> +		spanId = convertToString(traceData["span_id"])
这里可以用`hex.DecodeString`来解析spanid

2023-11-01 16:16 UTC, liuwenping commented on pkg/libgse/output/bkcollector/data.go
> +		parentSpanId = convertToString(traceData["parent_span_id"])
同理，hex.DecodeString

2023-11-01 16:16 UTC, liuwenping commented on pkg/libgse/output/bkcollector/data.go
> +		traceId = convertToString(traceData["trace_id"])
同理，使用hex.DecodeString

2023-11-01 16:16 UTC, liuwenping commented on pkg/libgse/output/bkcollector/data.go
> +	var result = make([]attribute.KeyValue, 0)
make的时候，大小是固定的，建议直接指定大小，而不是写0

从底下的for循环来看，这里是和入参attributes的大小一一对应

2023-11-01 16:16 UTC, liuwenping commented on pkg/libgse/output/bkcollector/data.go
> +func convertToString(value interface{}) string {
底下的实现，遍历的type并不是很全，比如string类型的情况，如果走了这个方法，就直接返回空字符串了。

类似的功能，建议google搜索一下，有没有类似的实现

2023-11-03 07:59 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/bkcollector.go
> +	exp, err := otlptrace.New(context.Background(), client)
直接 `return otlptrace.New(context.Background(), client)`

2023-11-03 08:00 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/bkcollector.go
> +			logp.Err("parse log data items to error! items:%v", eventItems)
无需要使用 `!` 来体现错误，`logp.Err` 本身足以

2023-11-03 08:01 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/bkcollector.go
> +				logp.Err("parse log to TraceData error! log:%v", log)
这里为什么不把 err 打印出来？

2023-11-03 08:01 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/bkcollector_test.go
> +//	func TestCreateSpanContext(t *testing.T) {
留下这个注释的目的是？

2023-11-03 08:02 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/bkcollector_test.go
> +	assert.Equal(t, "*otlptrace.Exporter", reflect.TypeOf(result).String())
这种算是什么验证？

2023-11-03 08:03 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/config.go
> +	EventBufferMax int32  `config:"eventbuffermax"`
为什么其他熟悉都是下划线，这个就不需要了？

2023-11-03 08:05 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/data.go
> +func convertToString(value interface{}) string {
感觉这里的类型断言还不是很完整，有验证过可能出现数据类型吗

2023-11-03 08:06 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/data.go
> +	spanContext := otelTrace.NewSpanContext(spanContextConfig)
像这种其实直接 `return otelTrace.NewSpanContext(spanContextConfig)` 会更简洁一点

2023-11-03 08:06 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/data.go
> +		_value := attribute.StringValue(v)
不建议在 golang 中使用下划线变量

2023-11-03 08:07 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/data.go
> +		_value := attribute.StringValue(v)
不知道怎么声明变量的话，直接 `Value: attribute.StringValue(v)` 也能解决问题

2023-11-03 08:08 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/data.go
> +		logp.Err("Parent_span_id cannot be converted to hexadecimal data,  Parent_span_id:%v", t.ParentSpanId)
那 err 是什么打出来是不是会更好一点

2023-11-03 08:08 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/data.go
> +		logp.Err("span_id cannot be converted to hexadecimal data,  span_id:%v", t.SpanId)
同下

2023-11-03 08:08 UTC, chenjiandongx commented on pkg/libgse/output/bkcollector/data.go
> +		logp.Err("trace_id cannot be converted to hexadecimal data,  trace_id:%v", t.TraceId)
同下

2023-11-03 10:19 UTC, liuwenping requested changes

2023-11-03 10:19 UTC, liuwenping commented on pkg/libgse/output/bkcollector/bkcollector_test.go
> +//// Tencent is pleased to support the open source community by making
这个文件为啥注释多了`//`

2023-11-03 10:19 UTC, liuwenping commented on pkg/libgse/output/bkcollector/bkcollector_test.go
> +//	func TestCreateSpanContext(t *testing.T) {
不要的内容，直接删除

2023-11-03 10:19 UTC, liuwenping commented on pkg/libgse/output/bkcollector/bkcollector.go
> +	dataType   string = "log_v2"
变量命名，可以增加default前缀

另外，常量，建议使用大写的方式

2023-11-04 02:07 UTC, liuwenping approved these changes

2023-11-04 02:07 UTC, merged